{% set name = "Flask-Login" %}
{% set version = "0.6.3" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: 5e23d14a607ef12806c699590b89d0f0e0d67baeec599d75947bf9c147330333

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask >=1.0.4
    - werkzeug >=1.0.1

test:
  imports:
    - flask_login
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User session management for Flask
  dev_url: https://github.com/maxcountryman/flask-login
  doc_url: https://flask-login.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
    - xylar
