{% set name = "Flask-Login" %}
{% set version = "0.6.0" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: aa84fcfb4c3cf09ca58c08e816b7bce73f1349ba1cf13d00d8dffc5872d5fcf6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - flask

  run:
    - python
    - flask

test:
  imports:
    - flask_login

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User session management for Flask
  dev_url: https://github.com/maxcountryman/flask-login
  doc_url: https://flask-login.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
