travis:
  secure:
    BINSTAR_TOKEN: rIxMsfoxtFo3oMvzRKAAkZUacf+WF/YG5gjFb4sUm9pt3AU2gOZ9iCNX3Cp0LmmfwZ1T1Pac8htwRHB0A1TmE5dcaYP5Cgrog5zVwtKVFsAVJ3U8vc7USzSMKfTCmxc3Q6dzpCAPLG67goDpztIMULA/wmcCwucGhzLpv3WHXl7IFws93xVA+v1LO2jFekVe6zMcO7xgeOhwI8PF2G+LWw9+bu2ii5quLDDTNzRdMXB12joJqaoAuWOOHiRFmlB/KDiKY5xmfbiyLiGyn1EQMFjlCAdF4KcX++biJIZ5Yjz77Agirrau80N6iNdzlRNqEADNot44j3hvQeuW4hgCz5w1Cbdh0b/DVYvAgs2M1+lkWRs9idnQRHcQkOcp+tT4YrnRfMLIGmOGUhGX7hqDyjIyzRqSbuezIBvZnRYX0DcLFCegDFpcFPmcyyHCUD/yEMKKQ+VPQSpATgImEfMQ6nJNSa2USSl2+UoxPyvPjIDKMDYWUz9VobywsmEbFybabcqJEW7iavzds0Ev6fd9SfndmWJ0EuFjV6J0c0b38oB1HEFb0mkxb21uRr38L/y+w6QUv3xgFGKAKAtaZXfKoC0R1HyGgQUQAbRSEyDtCYk+5IuD3jOY7hs+tjGoc2il8y+LTcykoUDbvV9LdpcOG1wC3QPmo9o0NebZrjr1884=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
